### ISSUE TITLE
overlay not working 

### ISSUE THREAD

**Issue by markos10l** [FearNixx/vigilant-bans#9]
followed all the steps the  when i click on start layout it doesn't work   + i have an other question 
does in this version the simple layout does have summoners spells ? cz i already know who to run it in the league of legends pick and ban and i didn't wanted to use it just because that layout ( not the europe one ) does have sums

**Comment by MarkTwoFive** [comment]
Hi 👋,

firstly, please elaborate on your issue. Can you for example provide some logs on any error that is showing up?
Or describe what exactly is not working as intended?
Version ``1.0.3`` appeared to be working fine for most of the users a week ago. 🤔

Secondly: This tool manages an installation of the ban-pick-tool from the volunteers. That means that whatever you found displeasing in the plain tool, would also be present when you use vigilant-bans - because the actual tool is the same. (Aside from the installation process of course.) 🤔

**Comment by markos10l** [comment]
yeah everything is working now tnks
